// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3IlT7slRhdYqlYsyjBUMbStNfU50D2Y',
    appId: '1:822339736451:web:b762172cad8498282d5cb6',
    messagingSenderId: '822339736451',
    projectId: 'cred-cee95',
    authDomain: 'cred-cee95.firebaseapp.com',
    storageBucket: 'cred-cee95.firebasestorage.app',
    measurementId: 'G-S155PS6K7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3z55Q_ubEK6RyrglQewilSbnisMJLjnM',
    appId: '1:822339736451:android:2c2a46e5df88d47e2d5cb6',
    messagingSenderId: '822339736451',
    projectId: 'cred-cee95',
    storageBucket: 'cred-cee95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqs7ke4dMdl7Aq_Cv9FfxUAz7dnhk6APw',
    appId: '1:822339736451:ios:5ae7c992f8fd8ce42d5cb6',
    messagingSenderId: '822339736451',
    projectId: 'cred-cee95',
    storageBucket: 'cred-cee95.firebasestorage.app',
    iosBundleId: 'com.example.credShowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqs7ke4dMdl7Aq_Cv9FfxUAz7dnhk6APw',
    appId: '1:822339736451:ios:5ae7c992f8fd8ce42d5cb6',
    messagingSenderId: '822339736451',
    projectId: 'cred-cee95',
    storageBucket: 'cred-cee95.firebasestorage.app',
    iosBundleId: 'com.example.credShowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe3IlT7slRhdYqlYsyjBUMbStNfU50D2Y',
    appId: '1:822339736451:web:4c314380a62243bb2d5cb6',
    messagingSenderId: '822339736451',
    projectId: 'cred-cee95',
    authDomain: 'cred-cee95.firebaseapp.com',
    storageBucket: 'cred-cee95.firebasestorage.app',
    measurementId: 'G-TPBJ0F2FTL',
  );
}
